// NOTE: .NET Core 3.1 has Span<T>, but is tested against our .NET Standard 2.0 assembly.
//#if NETCOREAPP2_1_OR_GREATER || NETSTANDARD2_1_OR_GREATER
#if NET6_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER

using System;

using NUnit.Framework;

using Org.BouncyCastle.Security;
using Org.BouncyCastle.Utilities;
using Org.BouncyCastle.Utilities.Encoders;

namespace Org.BouncyCastle.Crypto.Utilities.Tests
{
    [TestFixture]
    public class Lib25519Test
    {
        private readonly SecureRandom Random = new SecureRandom();

        /// <summary>
        /// Test interoperability with DH keypairs generated by the reference implementation.
        /// </summary>
        [Test]
        public void DHCompatibility()
        {
            Span<byte> pkA = Hex.DecodeStrict("A7903A3BB3A1F13C8762233FFCD00161F5E02F15A8B481D92AA4C4377CF9751C");
            Span<byte> pkB = Hex.DecodeStrict("FE0A4B000F033F5D9B1D87C6035E9197AB603F7F453F3723E61BA8C6FF6F8435");
            Span<byte> skA = Hex.DecodeStrict("B02B0874F3DB3E679200393A95E28B682DFF726CBBFBDADE042ACA2203A477C0");
            Span<byte> skB = Hex.DecodeStrict("A3B650EB7EB3D39486CCCEE16347FEA8951C3E6FE69A162F3029BEF946DA0EC1");
            Span<byte> k = Hex.DecodeStrict("B666ECF65932E33E44C962E2007929E081D21BA6EE335A28358835307F935B4D");

            Assert.AreEqual(Lib25519.DHPublicKeyBytes, pkA.Length);
            Assert.AreEqual(Lib25519.DHPublicKeyBytes, pkB.Length);
            Assert.AreEqual(Lib25519.DHSecretKeyBytes, skA.Length);
            Assert.AreEqual(Lib25519.DHSecretKeyBytes, skB.Length);
            Assert.AreEqual(Lib25519.DHBytes, k.Length);

            // We generate the same shared secret with the reference keys
            {
                Span<byte> kA = stackalloc byte[Lib25519.DHBytes];
                Span<byte> kB = stackalloc byte[Lib25519.DHBytes];

                Lib25519.DH(kA, pkB, skA);
                Assert.That(k.SequenceEqual(kA));

                Lib25519.DH(kB, pkA, skB);
                Assert.That(k.SequenceEqual(kB));
            }
        }

        /// <summary>
        /// Test self-consistent behaviour for this implementation's 'DH' methods.
        /// </summary>
        [Test]
        public void DHConsistency()
        {
            Span<byte> pkA = stackalloc byte[Lib25519.DHPublicKeyBytes];
            Span<byte> pkB = stackalloc byte[Lib25519.DHPublicKeyBytes];
            Span<byte> skA = stackalloc byte[Lib25519.DHSecretKeyBytes];
            Span<byte> skB = stackalloc byte[Lib25519.DHSecretKeyBytes];
            Span<byte> kA = stackalloc byte[Lib25519.DHBytes];
            Span<byte> kB = stackalloc byte[Lib25519.DHBytes];

            for (int i = 0; i < 10; ++i)
            {
                Lib25519.DHKeyPair(pkA, skA);
                Lib25519.DHKeyPair(pkB, skB);

                Lib25519.DH(kA, pkB, skA);
                Lib25519.DH(kB, pkA, skB);

                // Alice and Bob agree on the shared secret
                Assert.That(kA.SequenceEqual(kB));
            }
        }

        /// <summary>
        /// Test interoperability with a keypair and message signed by the reference implementation.
        /// </summary>
        [Test]
        public void SignCompatibility()
        {
            Span<byte> pk = Hex.DecodeStrict(
                "B395CDA6065928050FA680D91652A393E70902D7448226B60661277114AA9251");
            Span<byte> sk = Hex.DecodeStrict(
                "6BBA3FA19FA4D27B326E44F80570626C67E5419763C6092EBF5DB23D56F0C430" +
                "B395CDA6065928050FA680D91652A393E70902D7448226B60661277114AA9251");
            Span<byte> m = Hex.DecodeStrict(
                "60CC404FA136D1CC0894A7C63DAC9DABD5C330B4BDB01154D70B573C492103D3" +
                "CCA003D13CDCE62C4E9D95C07C1E7A71FADE4C11C44737589E9A5CE9EBBD0CFB" +
                "EC4843E31B111DDA21050E829334F5EF41CE54545AFC49C4544B84AE89A4E37A" +
                "2029582C6A62CB064479BC4BAC26E309B47BCC332F798CDC58F8FC1067900F3D" +
                "7C71CD7C3F9517582D716984294B357C6C8F788C966F53E5D741DF4A536CC8D7" +
                "3A9675FA24D506CA54290CC7C1C5A208E66FE4BE1BC8D12918AAD2958784FB15" +
                "ED811A4CC87F16C411D7ED5B2666724C54C91B08745FD792E61C1BB789821A3D" +
                "B7D5DFAA1390D4F91AC0F55263FD8A95CF393696BEBA9AB6F4AC2835490A4010");
            Span<byte> sm = Hex.DecodeStrict(
                "CEF1E171064E34EBC6C1DDE98B0A97874E6E1C88EEC62C420CDF2129D0695D07" +
                "6D5D1F773F0E7196927239C5CA371414D62ABC8314BC72D22EF061D5F65DB004" +
                "60CC404FA136D1CC0894A7C63DAC9DABD5C330B4BDB01154D70B573C492103D3" +
                "CCA003D13CDCE62C4E9D95C07C1E7A71FADE4C11C44737589E9A5CE9EBBD0CFB" +
                "EC4843E31B111DDA21050E829334F5EF41CE54545AFC49C4544B84AE89A4E37A" +
                "2029582C6A62CB064479BC4BAC26E309B47BCC332F798CDC58F8FC1067900F3D" +
                "7C71CD7C3F9517582D716984294B357C6C8F788C966F53E5D741DF4A536CC8D7" +
                "3A9675FA24D506CA54290CC7C1C5A208E66FE4BE1BC8D12918AAD2958784FB15" +
                "ED811A4CC87F16C411D7ED5B2666724C54C91B08745FD792E61C1BB789821A3D" +
                "B7D5DFAA1390D4F91AC0F55263FD8A95CF393696BEBA9AB6F4AC2835490A4010");

            Assert.AreEqual(Lib25519.SignPublicKeyBytes, pk.Length);
            Assert.AreEqual(Lib25519.SignSecretKeyBytes, sk.Length);
            Assert.AreEqual(Lib25519.SignBytes + m.Length, sm.Length);

            // We can open the reference message with reference public key
            {
                Span<byte> m1 = stackalloc byte[sm.Length];
                Assert.True(Lib25519.SignOpen(m1, out int m1len, sm, pk));
                Assert.AreEqual(m.Length, m1len);
                Assert.That(m.SequenceEqual(m1[..m1len]));
            }

            // We can sign and open using the reference keys
            {
                Span<byte> sm2 = stackalloc byte[sm.Length];
                Lib25519.Sign(sm2, out int sm2len, m, sk);
                Assert.AreEqual(sm.Length, sm2len);
                // NB: Don't require deterministic signing

                Span<byte> m2 = stackalloc byte[sm.Length];
                Assert.True(Lib25519.SignOpen(m2, out int mlen2, sm2, pk));
                Assert.AreEqual(m.Length, mlen2);
                Assert.That(m.SequenceEqual(m2[..mlen2]));
            }

            // Modifying the signed message causes verification to fail
            {
                Span<byte> m3 = stackalloc byte[sm.Length];
                Span<byte> sm3 = sm.ToArray();

                for (int i = 0; i < 10; ++i)
                {
                    // Flip a random bit of the signed message
                    int bit = Random.Next(sm.Length * 8);
                    sm3[bit >> 3] ^= (byte)(0x01 << (bit & 7));

                    // Check the signed message can no longer be opened
                    m3.Fill(0xFF);
                    Assert.False(Lib25519.SignOpen(m3, out int mlen3, sm3, pk));
                    Assert.AreEqual(-1, mlen3);
                    Assert.That(Arrays.AreAllZeroes(m3[..sm3.Length]));

                    // Restore the signed message
                    sm3[bit >> 3] ^= (byte)(0x01 << (bit & 7));
                }
            }
        }

        /// <summary>
        /// Test self-consistent behaviour for this implementation's 'Sign' methods.
        /// </summary>
        [Test]
        public void SignConsistency()
        {
            Span<byte> pk = stackalloc byte[Lib25519.SignPublicKeyBytes];
            Span<byte> sk = stackalloc byte[Lib25519.SignSecretKeyBytes];

            int mLength = 1000;
            int smLength = mLength + Lib25519.SignBytes;

            Span<byte> m_in = stackalloc byte[mLength];
            Span<byte> sm = stackalloc byte[smLength];
            Span<byte> m_out = stackalloc byte[smLength];

            for (int i = 0; i < 10; ++i)
            {
                Random.NextBytes(m_in);

                // Check signed message has the expected length
                Lib25519.SignKeyPair(pk, sk);
                Lib25519.Sign(sm, out int smlen, m_in, sk);
                Assert.AreEqual(smLength, smlen);

                // Check the signed message can be opened to the correct original message
                Assert.True(Lib25519.SignOpen(m_out, out int mlen, sm, pk));
                Assert.AreEqual(mLength, mlen);
                Assert.That(m_in.SequenceEqual(m_out[..mlen]));

                // Modifying the signed message causes verification to fail
                {
                    // Flip a random bit of the signature part of the signed message
                    int sigBit = Random.Next(Lib25519.SignBytes * 8);
                    sm[sigBit >> 3] ^= (byte)(0x01 << (sigBit & 7));

                    // Check the signed message can no longer be opened
                    m_out.Fill(0xFF);
                    Assert.False(Lib25519.SignOpen(m_out, out int mlen2, sm, pk));
                    Assert.AreEqual(-1, mlen2);
                    Assert.That(Arrays.AreAllZeroes(m_out[..sm.Length]));

                    // Restore the signature part of the signed message
                    sm[sigBit >> 3] ^= (byte)(0x01 << (sigBit & 7));

                    // Flip a random bit of the message part of the signed message
                    int msgBit = Random.Next(mLength * 8);
                    sm[Lib25519.SignBytes + (msgBit >> 3)] ^= (byte)(0x01 << (msgBit & 7));

                    // Check the signed message can no longer be opened
                    m_out.Fill(0xFF);
                    Assert.False(Lib25519.SignOpen(m_out, out int mlen3, sm, pk));
                    Assert.AreEqual(-1, mlen3);
                    Assert.That(Arrays.AreAllZeroes(m_out[..sm.Length]));

                    // Restore the message part of the signed message
                    sm[Lib25519.SignBytes + (msgBit >> 3)] ^= (byte)(0x01 << (msgBit & 7));
                }
            }
        }
    }
}

#endif
