parameters: 
  signSteps: []
  
steps:
- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- script: nbgv cloud -c
  displayName: Set Version
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- powershell: echo "##vso[build.updatebuildnumber]$Env:GitBuildVersionSimple"
  displayName: Set Version for Mapped
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false), eq(variables['IsMatchingBase'], true))

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: .\crypto\src\crypto.csproj
    packDirectory: $(Build.ArtifactStagingDirectory)\Packages
    configuration: $(BuildConfiguration)
    arguments: /p:PackageId="Portable.BouncyCastle" 
  displayName: Build  
  
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: .\crypto\test\crypto.test.csproj
    arguments: -c $(BuildConfiguration) --collect:"Code Coverage" -s $(System.DefaultWorkingDirectory)\CodeCoverage.runsettings /p:DebugType=portable
  displayName: Run Tests
  
- ${{ parameters.signSteps }}

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Packages
  condition: eq(variables['system.pullrequest.isfork'], false)
