parameters: 
  signSteps: []
  
steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.7.0
  inputs:
    versionSpec: 4.7.0

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: scripts/setversion.csproj
    arguments: -c $(BuildConfiguration)   
  displayName: Set Version
  condition: eq(variables['system.pullrequest.isfork'], false)

- powershell: |        
    mkdir $(Build.ArtifactStagingDirectory)\Packages
    msbuild .\BouncyCastle.sln /restore /p:Configuration=$(BuildConfiguration) 
    msbuild .\crypto\src\crypto.csproj /m /t:pack /p:Configuration=$(BuildConfiguration) /p:PackageId="Portable.BouncyCastle" /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\Packages
  
  displayName: Build
  
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: .\crypto\test\crypto.test.csproj
    arguments: -c $(BuildConfiguration) --no-build --no-restore
  displayName: Run Tests
  
- ${{ parameters.signSteps }}

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Packages
  condition: eq(variables['system.pullrequest.isfork'], false)
