theme: jekyll-theme-cayman
title: Bouncy Castle
description: .NET Library Documentation
github:
  repository_name: bcgit/bc-csharp
  owner_url: https://www.bouncycastle.org
  owner_name: The Legion of the Bouncy Castle
plugins:
  - jemoji
